---
title: "Curriculum Vitae"
author: "Juan Carlos Castillo Valenzuela"
date: "2024-05-23"
format: pdf
header-includes:
  - \usepackage{pdfpages}
---

# INFORMACION PERSONAL:

**NOMBRE:** Juan Carlos Castillo Valenzuela

**CÉDULA DE IDENTIDAD O RUN:** 10.612.714-K

**LUGAR y FECHA DE NACIMIENTO:** Viña del Mar, 30 Nov. 1973

**NACIONALIDAD:** Chileno

**ESTADO CIVIL:** Divorciado

**TITULOS o GRADOS ACADÉMICOS:** 

- Doctor en Sociología Universidad de Humboldt Alemania

- Máster en Gestión Pública Universidad de Potsdam Alemania

- Licenciado en Psicología Universidad Católica de Valparaíso

**CARGO ACTUAL EN LA U. DE CHILE:** 

- Profesor Asociado Departamento de Sociología

- Director de Investigación y Publicaciones Facultad de Ciencias Sociales

**DIRECCIÓN ACADÉMICA:** Ignacio Carrera Pinto 1045 Ñuñoa

**FONO:** +56 9 79712541

**E-MAIL:** juancastillov@uchile.cl

**DIRECCIÓN PARTICULAR:** Villaseca 975 F Ñuñoa

**FONO:** +56 9 7971 2541

**SITIO WEB ACADEMICO:** [www.jc-castillo.com](http://www.jc-castillo.com)

# ESTUDIOS REALIZADOS:

## 2.1. ESTUDIOS SUPERIORES UNIVERSITARIOS FORMALES CONDUCENTES A GRADO TÍTULO O DIPLOMA:

**2005 - 2010**  
Doctorado en Sociología  
Berlin Graduate School of Social Sciences, Departamento de Metodología del Instituto de Ciencias Sociales, Universidad de Humboldt, Berlín.  
Título de la tesis doctoral: “The legitimacy of economic inequality. An empirical social justice approach to the case of Chile” (Calificación: Summa cum Laude).

**1999 - 2000**  
Master en Gestión Pública – Universidad de Potsdam, Alemania. 

**1991 - 1997**  
Licenciado en psicología – Universidad Católica de Valparaíso, Chile.

## 2.2. ACTIVIDADES DE PERFECCIONAMIENTO: Indique la entidad en que se realizó. Incluya una breve descripción de la actividad área de especialidad lugar y fechas de inicio y término. Incluya separadamente ya modo de ejemplo los cursos de formación docente (en particular para las jerarquías de ayudante instructor y profesor asistente) y los de formación global (idiomas redacción científica etc.).

- Taller : “Rol del tutor como guía de tesis”. 3 de Agosto de 2018, Centro de Desarrollo Docente, Pontificia Universidad Católica de Chile. 

- Workshop: “Using the International Databases from Large-Scale Education Studies for Secondary Analysis”. April 13-17 2012, Vancouver, AERA Conference.

- 36th Spring Seminar: “Topics in Advanced Categorical Data Analysis (CDA)”. Docentes: Linda M. Collins & Allan McCutcheon. 26 de Febrero – 9 de Marzo, 2007 en Köln, Zentrales Archiv für Empirische Sozialforschung.

- Workshop “Latent Variable Modeling with Mplus”. Docentes: Profesores Bengt y Linda Muthén. 10 - 12 Septiembre 2007 - School of Economics, University of Florence.

- 37th Spring Seminar “Generalized Latent Variable Modeling”. Docente: Prof. Jeroen Vermunt. 10 - 14 Marzo 2008 en Köln, Zentrales Archiv für Empirische Sozialforschung.

# DISTINCIONES OBTENIDAS:

## 3.1. BECAS: Institución que la otorgó área de actividad objetivos y fechas entre las cuales hizo uso de ella.

**2024**  
Beca del DAAD (Servicio Alemán de Intercambio Académico) para estadía de investigación en la Universidad de Bremen, Alemania.

**2022**  
Beca del Instituto de Investigación en Cohesión Social de la Universidad de Bremen para estadía de investigación como profesor visitante.

**2017**  
Beca del DAAD (Servicio Alemán de Intercambio Académico) para estadía de investigación en la Universidad de Humboldt, Alemania.

**2016**  
Beca del KAAD (Servicio Católico de Intercambio Académico) para estadía de investigación en la Universidad de Bremen, Alemania.

**2014**  
Beca Volkswagen Stiftung para presentación de investigación en Conferencia “Re-Thinking Social Inequality” en Hannover, Alemania.

**2009 - 2010**  
Beca de docencia, Berlin Graduate School of Social Sciences.

**2009 - 2010**  
Beca de finalización de doctorado, Berlin Graduate School of Social Sciences.

**2006**  
Beca de calificación a la docencia, Berlin Graduate School of Social Sciences.

**2005 - 2009**  
Beca de doctorado KAAD (Servicio Católico de Intercambio Académico).  

**1999 - 2000**  
Beca de Maestría DSE (Fundación Alemana para el Desarrollo Internacional).

## 3.2. PREMIOS y OTRAS DISTINCIONES: Señale nombre del premio o distinción, la institución que los otorgó y la fecha de recepción. Incluya conferencias importantes que le hayan sido solicitadas.

**2023**  
Nominado y electo presidente del comité de investigación 42 (RC42-Social Psychology) de la International Sociological Association (ISA).

**2020**  
Invitado a participar como experto en temas de desigualdad económica a la conferencia Tokio LAINAC. Universidad de Tokio, Japón.

**2016**  
Primer lugar en concurso de investigación FONDECYT Regular, grupo de estudio de sociología.

**2014**  
Best paper award, Police Practice and Research Journal junto, a Ron Factor y Arye Rattner.

**2014**  
Premio Edgardo Catterberg a mejor artículo de conferencia – WAPOR (World Association for Public Opinion Research – Latin America), junto a Matías Bargsted & Nicolas Somma.

**2000**  
Premio al mejor estudiante de maestría, Facultad de Economía y Administración Universidad de Potsdam, Alemania.

# BREVE CRONOLOGÍA LABORAL:

Indique someramente año, labor realizada, cargo desempeñado, etc. (más adelante se explicitarán de acuerdo a criterios académicos).

**2023-**  
Director de Investigación y Publicaciones Facultad de Ciencias Sociales, Universidad de Chile.

**2022-**  
Profesor Asociado (planta) carrera ordinaria, departamento de Sociología, Universidad de Chile.

**2019 - 2021**  
Profesor Asociado (contrata) carrera ordinaria, departamento de Sociología, Universidad de Chile.

**2018**  
Seleccionado en concurso para profesor de metodología cuantitativa en el Departamento de Sociología, Universidad de Chile.

**2018 - 2019**  
Director del grupo de estudio de Sociología de FONDECYT.

**2016 - 2017**  
Miembro del grupo de estudio de Sociología de FONDECYT.

**2014 - 2018**  
Profesor asistente, Instituto de Sociología, Pontificia Universidad Católica de Chile.

**2013 -**  
Subdirector e Investigador Principal FONDAP COES, Centro para el Estudio del Conflicto y la Cohesión Social.

**2012 - 2013**  
Coordinador área de investigación Centro de Medición Mide-UC, Facultad de Ciencias Sociales, P. Universidad Católica de Chile.

**2011 - 2013**  
Profesor asistente adjunto, Escuela de Psicología, P. Universidad Católica de Chile.

**2010 - 2011**  
Investigador asociado Centro de Medición Mide-UC, Facultad de Ciencias Sociales, P. Universidad Católica de Chile.

**2005 - 2009**  
Investigador asociado en proyecto comparativo de opinión pública sobre justicia social (International Social Justice Project www.isjp.de) – Instituto de Ciencias Sociales, Universidad de Humboldt Berlin.

**2004 - 2005**  
Coordinador de proyectos de intervención social – Estudios Sociales Aplicados, Valparaíso, Chile.

**2000 - 2004**  
Director regional y sub director nacional del programa “Adopta un herman@” – Fundación para la Superación de la Pobreza, Valparaíso / Santiago, Chile.

**1998 - 1999**  
Programa “Servicio País” – Fundación para la Superación de la Pobreza.

# ACTIVIDADES ACADÉMICAS:

## 5.1. DOCENCIA:

### 5.1.1. Enumere, detalladamente, las asignaturas de pre y post grado impartidas durante todos los años de vida académica. Indicar escuela, facultad, instituto, universidad, año, número aproximado de alumnos, horas de docencia directa que dicta en su curso y las horas de la asignatura según el respectivo plan de estudios, tipo de participación en el curso (coordinador, responsable único, participación en docencia teórica, práctica, laboratorios, seminarios, actividades de terreno). 

Pregado Universidad de Chile

**2023**

- Electivo de profundización metodológica: Análisis de datos multinivel – responsable 21 estudiantes

- Estadística correlacional pregado sociología – responsable (dos secciones) 86 estudiantes

- Seminario de grado – responsable 3 estudiantes

- Seminario de título I – responsable 1 estudiante

- Seminario de título II – responsable 2 estudiantes

- Práctica profesional – responsable 2 estudiantes

**2022**  

- Estadística multivariada – responsable (dos secciones) 94 estudiantes

- Electivo de Profundización Metodológica - Diseño y Análisis de Encuestas Sociales – responsable 24 estudiantes

- Seminario de grado – responsable 2 estudiantes

- Seminario de título I – responsable 1 estudiante

- Seminario de título II – responsable 5 estudiantes

- Práctica profesional – responsable 7 estudiantes

**2021**  

- Estadística multivariada sección 1 – responsable 38 estudiantes

- Estadística multivariada sección 2 – responsable 37 estudiantes

- Electivo de Profundización Metodológica - Ciencia Social Abierta: Herramientas para la Reproducibilidad Colaboración y Comunicación de la Investigación Social – responsable 24 estudiantes

- Seminario de grado – responsable 6 estudiantes

- Seminario de título I – responsable 5 estudiantes

- Seminario de título II – responsable 5 estudiantes

- Práctica profesional – responsable 7 estudiantes

**2020**  

- Estadística multivariada sección 1 – responsable 45 estudiantes

- Estadística multivariada sección 2 – responsable 44 estudiantes

- Electivo de Profundización Metodológica - Ciencia Social Abierta: Herramientas para la Reproducibilidad Colaboración y Comunicación de la Investigación Social – responsable 41 estudiantes

- Seminario de grado – responsable 6 estudiantes

**2019** 

- Estadística multivariada – responsable 44 estudiantes

- Taller de investigación 1 – 2 estudiantes

- Taller de investigación 2 – 4 estudiantes

- Estrategias de Investigación Cuantitativa – 51 estudiantes

- Electivo de Profundización Metodológica - Análisis Multinivel – 28 estudiantes

Postgrado Universidad de Chile

**2023** 

- Electivo Métodos Multinivel – responsable 6 estudiantes

- Métodología I – profesor de cátedra 18 estudiantes

**2022**

- Tesis (proyecto) – 1 estudiante

**2021**  

- Tesis (proyecto) – 3 estudiantes

**2020**  

- Chile Hoy 1975-2020: Imaginarios sociológicos del régimen neoliberal chileno – profesor invitado 6 estudiantes

**2019**  

- Análisis Multivariable Aplicado a la Investigación Social módulo multinivel – profesor responsable 21 estudiantes

Postgrado Pontificia Universidad Católica de Chile

**2015 – 2018**  

- Modelos multinivel. Magíster en Sociología (responsable único 4 horas docencia semanal app. 20 alumnos). 

**2014 – 2018**  

- Modelos de ecuaciones estructurales. Magíster en Sociología. (responsable único 4 horas docencia semanal app. 20 alumnos). 

- Seminario de Tesis de Magíster I Instituto de Sociología. 

- Seminario de Tesis de Magíster II Instituto de Sociología. 

**2012 – 2013**  

- Seminario de Profundización metodológica. Doctorado en Psicología.

- Metodología cuantitativa avanzada 1. Doctorado en Psicología. (curso compartido 4 horas docencia semanal app. 20 alumnos)

- Metodología cuantitativa avanzada 2. Doctorado en Psicología. (curso compartido 4 horas docencia semanal app. 20 alumnos). 

Pregrado Pontificia Universidad Católica de Chile

**2015 – 2016**  

- Individuo y sociedad: Psicología social sociológica Instituto de Sociología. (responsable único 4 horas docencia semanal app. 60 alumnos).

**2014 – 2018**  

- Taller de titulación II Instituto de Sociología.

- Taller de titulación I Instituto de Sociología.

**2011 – 2012** 

- Taller de integración III (desarrollo de proyectos de investigación). Carrera de Psicología. (curso compartido 4 horas docencia semanal app. 60 alumnos).

Otros

**2006 – 2007**  

- Investigación social empírica. Instituto de Ciencias Sociales Universidad de Humboldt Berlin. (curso compartido 4 horas docencia semanal app. 60 alumnos)

**2005**  

- Modelos de desarrollo social. Carrera de Psicología P. Universidad Católica de Valparaíso. (responsable único 2 horas docencia semanal app. 15 alumnos).

### 5.1.2. Destaque aspectos específicos de su actividad docente que, a su juicio, reflejen su creatividad en este aspecto; v.gr.:

- *Creatividad docente*: en mis cursos de pre y postgrado utilizo una lógica de ciencia abierta, con texto y código de evaluaciones disponibles para los estudiantes, revisión ciega de pares y promoción de la colaboración. Más allá del análisis de datos, propongo una visión de productos de investigación con foco comunicacional durante el proceso de investigación y también luego de finalizado el producto. Hago mucho énfasis en visualización, transparencia y reproducibilidad.

- *Creación de cursos nuevos*: en mi paso por la Univesidad Católica generé los cursos de modelos multinivel y de ecuaciones estructurales para el postgrado en sociología, el curso “Individuo y sociedad” (psicología social sociológica) para el pregrado en sociología. En el caso de la Universidad de Chile he creado los siguientes cursos: Análisis Multinivel, Ciencia Social Abierta, y Encuestas Sociales. Además, participé en la adaptación de los cursos de Estadística Correlacional, Estadística Multivariada y Estrategias de Investigación Cuantitativa.

- *Tutorías*: realizo tutorías a tesistas de magister, a estudiantes de doctorado y a estudiantes de pregrado. En las tutorías promuevo instancias personalizadas y también grupales para que los y las estudiantes puedan aprender de los demás y comentar también sus trabajos.

- *Coloquio de investigación*: como parte de la formación en investigación, durante los años 2020-2022 coordiné una instancia semanal de presentación de resultados de investigación para tesistas e invitados externos, llamada “Coloquio de investigación en desigualdad y ciudadanía”.

### 5.1.3.

A. TESIS DIRIGIDAS DE MAGISTER: (M.A., M.Sc.), DOCTORADO (Ph.D), COMO PROFESOR RESPONSABLE.

He participado en una serie de comisiones de tesis, abajo listo solamente en las cuales he participado en calidad de director o co-guía:

•	Kevin Carrasco (2023). Aceptar la diversidad en el vecindario: Procesos de socialización política de actitudes hacia la diversidad social en estudiantes chilenos. Magister en Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Francisco Meneses (2023). El lenguaje como brecha de la formación ciudadana: El rol de la comprensión lectora sobre las habilidades para la ciudadanía y el conocimiento cívico.. Magister en Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Anais Herrera (2023). ¿Qué pueden hacer las escuelas para promover actitudes positivas hacia la igualdad de derechos?. Magister en Ciencias Sociales - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Guillermo Beck (2019). Explorando la asociación entre redes de contacto ocupacionales y la justificación de la desigualdad social en Chile. Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile.

•	Rodrigo Yanez (2019). Inégalité subjective au Chili. Représentation des différences sociales (in)justes à travers le temps. Doctorado en Sociología - EHESS. Paris. (co-director).

•	Francisca Castro (2018). ¿Menos confianza, menos Estado? El impacto de la corrupción sobre las preferencias redistributivas. Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile.

•	Julio Iturra (2018). Estatus social subjetivo y Percepción de meritocracia: El caso de Chile. Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile.

•	Sebastian Rojas (2018). La dimensión subjetiva de la desigualdad de género en ingresos: Factores individuales asociados a evaluación de lo percibido y lo justo. Magister en Sociología - Pontificia Universidad Católica de Chile. Santiago de Chile.

•	Miranda, D. (2018) The civic and civil dimensions of youth participation. Doctorado en sociología, P. Universidad Católica de Chile. 

•	Plaza, A. (2018) Movilidad social y preferencias por la redistribución: Efectos individuales y contextuales. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Franetovic, G. (2018) Desigualdad, desarrollo económico y preferencias redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Muñoz, E. (2018) Evaluaciones de justicia distributiva sobre las pensiones de vejez en Chile. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Sandoval, D. (2017) Merezco estar aquí: Un estudio multinivel sobre la relación entre meritocracia y educación. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Montedónico, S. (2017) Contexto Polı́tico Institucional y Preferencias Redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Acevedo, F. (2017) Compromiso Cívico Juvenil en Chile: una aproximación desde los recursos. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Placencio, M. (2016) Legitimidad del Sistema Económico y Participación Ciudadana: Una aproximación a la relación entre percepciones individuales y actividad política en Chile. Magíster en Sociología, P. Universidad Católica de Chile. 

•	Viertel, F. (2016) Medición en ciudadanía: Equivalencia y propiedades psicométricas de una escala de percepción en estudiantes. Magíster en Medición, Escuela de Psicología, P. Universidad Católica de Chile. 

•	Santander, E. (2015) ¿Qué puede hacer la cultura de la escuela para aumentar la participación política de sus estudiantes? Magíster en Sociología, P. Universidad Católica de Chile. 

•	Torres, A. (2014) Aspectos subjetivos de la meritocracia y su relación con la percepción de desigualdad en Chile. Magíster en Psicología Social-Comunitaria, P. Universidad Católica de Chile. 

•	Yañez, R. (en curso) Construcción de juicios de justicia y emergencia de sentimientos de injusticia frente a la desigualdad social. Doctorado en Sociología, EHESS Paris (codirector).

B. MEMORIAS DIRIGIDAS COMO PROFESOR RESPONSABLE CONDUCENTES A GRADO O TÍTULO: Se precisa conocer los trabajos específicos que dirigió, con el mayor detalle posible en cada caso.

•	Larenas, P. (2024). El conflicto intercultural entre el estado chileno y la causa mapuche por autodeterminación. Licenciatura en Sociología -  Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile.

•	Andreas Lafferte (2023). Ellos contra nosotros: las percepciones del conflicto social. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Karen Tapia (2022). Bienestar, trabajo doméstico y uso del tiempo: un análisis cuantitativo del bienestar de las mujeres en Chile. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Javiera Urrutia (2022). Determinantes de la percepción de seguridad frente al delito en la Región Metropolitana. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Sebastian Cortinez (2022). El efecto de las creencias meritocráticas sobre las atribuciones de pobreza y riqueza. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Catalina Miranda (2022). Factores determinantes de las trayectorias de deserción permanente en educación superior: El efecto de las ayudas financieras estatales y la política de gratuidad. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Martin Venegas (2022). ¿Quién justifica qué? El rol del sentido de injusticia en las justificaciones de violencia en contexto de protesta. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Simon Varas (2021). Enfermedades crónicas no transmisibles y el efecto protector de la cohesión social en Chile. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Carlos Budnevich (2021). La composición social de las escuelas y su relación con el rendimiento académico en lenguaje y matemática de los estudiantes secundarios chilenos. Licenciatura en Sociología - Departamento de Sociología, Facultad de Ciencias Sociales, Universidad de Chile. Santiago de Chile.

•	Nogueira, A., & Lihn, T. (2018). Prácticas de inclusión y exclusión de estudiantes en situación de migración: Un estudio de caso en dos escuelas municipales de la comuna de renca en santiago [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	González Ide, A., & González, D. (2018). Chile: Sociodemografía e inser- ción laboral de los inmigrantes re- cientes. El caso de los haitianos y venezolanos. [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Concha, J. F., & Saavedra, M. B. (2018). Facilitadores y limitantes en la contratación de migrantes desde el empleador del sector terciario de producción [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Contreras, P., & Terra, V. (2017). Construyendo Involucramiento Comunitario: Casos de Parque Metropolitano Cerro Chena y Mapocho Limpio [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	García, J., & Riquelme, V. (2017). Relevancia de la Convocatoria de Investigación en Educación del Consejo Nacional de Educación en la trayectoria académica de los finalistas adjudicados y no adjudicados de los años 2014. 2015 y 2016. [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Moller, A., & Zúñiga, G. (2017). Mecanismos de Participación Ciudadana en Proyectos de Inversión en Chile Propuesta Metodológica a partir  de proyectos de inversión de GHD [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Muñoz, C., & Cofré, R. (2017). La Formación Continua en Docencia del Profesorado Universitario Efectos sobre la práctica y autopercepción docente [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Ajraz, N., & Sanchez, N. (2015). Prevención en salud mental en la Atención Primaria de Salud [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Amenábar, J., & Sánchez, J. (2015). Discusión teórica y empírica sobre la élite económica chilena [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Barros, M. J., & Torres, P. (2015). Todos somos amigos, pero unos más que otros	    Estudio	   exploratorio	   sobre	   segregación  en	   la	    sala	   de	   clases [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.

•	Acevedo, V., & Arellano, C. (2014). Evaluación de la implementación, gestión y utilización de la Ley 20.500 [Taller titulación - pregrado sociología]. Pontificia Universidad Católica de Chile.



## 5.2. Investigación: Señale las actividades de investigación en que ha participado indicando en cada caso la entidad donde realizó la investigación, calidad en que participó, fuente de financiamiento, materia específica investigada, objetivos de la misma y fechas de inicio y de término.

En todas mis investigaciones utilizo métodos de análisis cuantitativo aplicado a encuestas (datos primarios y secundarios). Hago énfasis en la investigación comparativa internacional, medición de variables latentes y encuestas factoriales.

**Línea principal:** Justicia distributiva y percepción de desigualdad económica.  
**Línea secundaria:** Formación ciudadana y cohesión social.

### Proyectos de investigación financiados en fondos concursables con revisión de pares:

**2023-2025**  
Investigador Principal Núcleo Milenio en Ciencias Sociales: Desigualdades y Oportunidades Digitales (NUDOS). 

**2020-2024**  
Investigador principal proyecto FONDECYT Regular 1210847:  
Meritocracia en la escuela (EDUMER): Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile (adjudicado en grupo de estudio de sociología).

**2019-2024**  
Investigador principal proyecto FONDAP COES: Centro para el estudio de Conflicto y Cohesión Social (ANID).

**2018-2021**  
Coinvestigador proyecto FONDECYT Regular 1181239: Socialización política y educación para la ciudadanía: El rol de la familia y de la escuela (adjudicado en grupo de estudio de sociología). Investigador principal: Cristián Cox. 

**2016-2019**  
Investigador principal proyecto FONDECYT Regular 1160921: Economía moral de la meritocracia y preferencias redistributivas (adjudicado en grupo de estudio de sociología). 

**2015-2017**  
Investigador patrocinante proyecto FONDECYT Postdoctorado 3160705: Elite Económica, Concentración de Ingresos y Tributación: Conflictos redistributivos en Chile (adjudicado en grupo de estudio de sociología).  Investigador principal: Jorge Atria.

**2013 - 2018**  
Investigador principal / subdirector proyecto FONDAP COES: Centro para el estudio de Conflicto y Cohesión Social (CONICYT).

**2013 - 2014**  
Investigador principal proyecto Apoyo a la Formación de Redes Internacionales entre Centros de Investigación (CONICYT DRI - Departamento de Relaciones Internacionales).

**2012 - 2015**  
Investigador principal proyecto FONDECYT de Iniciación 11121203: Social justice and citizenship participation: An international comparison with focus on the case of Chile (adjudicado en grupo de estudio de sociología). 

**2012 - 2015**  
Coinvestigador proyecto FONDECYT 1120630: Socialización política y experiencia escolar, Chile en contexto internacional - Investigador principal: Cristián Cox (adjudicado en grupo de estudio de sociología).

**2011 - 2012**  
Investigador principal proyecto Inicio 11/2011: Inequality social justice and political participation. Vicerrectoría de Investigación de la P. Universidad Católica de Chile. 

**2010 - 2011**  
Investigador principal proyecto Inicio 24/2010: Testing the stability of perception and justification of economic inequality in Chile: A cross-sectional time comparison. Vicerrectoría de Investigación de la P. Universidad Católica de Chile.

## 5.3. Creación

(no aplica)

## 5.4. Extensión y Divulgación: Enumere y describa las principales actividades de extensión señalando para cada caso la institución donde se realizó, su contenido, objetivo y fechas (podrán incluirse actividades tales como cursos breves, conferencias, publicaciones de difusión, etc. que Ud. haya impartido o hayan estado a su cargo).

**2024 Enero.** Taller Herramientas de Ciencia Abierta: Apertura y reproducibilidad de proyectos de investigación [Proyecto Ingeniería 2030 de la Facultad de Ingeniería de la Universidad de Valparaíso]. [https://uv.cl/archivo-noticias-uv/26426-director-de-investigacion-de-la-facultad-de-ciencias-sociales-uchile-dicto-taller-sobre-ciencia-abierta](https://uv.cl/archivo-noticias-uv/26426-director-de-investigacion-de-la-facultad-de-ciencias-sociales-uchile-dicto-taller-sobre-ciencia-abierta)
  
**2023 Enero.** Taller Diseño y gestión de proyectos de investigación abiertos [Escuela de Verano Conocimiento y Ciencia Abierta - Universidad Central].

**2023 Enero.** Conferencia Flujo y Componentes de la Investigación Abierta [9o Congreso de Bibliotecas Universitarias y Especializadas Universidad de Chile].

**2022 Enero.** Taller Protocolos reproducibles y reportes dinámicos con R / Rmarkdown [Laboratorio de Investigación Social Abierta (LISA) - COES]. [https://lisa-coes.github.io/presentaciones/tallerRmarkdown-IPOEnero2022/taller-reprod-enero2022.html](https://lisa-coes.github.io/presentaciones/tallerRmarkdown-IPOEnero2022/taller-reprod-enero2022.html)

**2022 Marzo.** Presentación Cohesión social en Chile en tiempos de cambio: Indicadores perfiles y factores asociados [Presentación Seminario CEPAL-COES]. [https://ocscoes.github.io/presentaciones/CEPAL2022cohesionELSOC.html](https://ocscoes.github.io/presentaciones/CEPAL2022cohesionELSOC.html)

**2022 Junio.** Curso Herramientas para la apertura del flujo de investigación científica [Presentación en el seminario: Ciencia abierta ¿es ciencia accesible?]. [https://lisa-coes.github.io/presentaciones/Ibero-MEX-Jun2022/iberomex2022.html](https://lisa-coes.github.io/presentaciones/Ibero-MEX-Jun2022/iberomex2022.html)

**2022 Septiembre.** Taller Preregistros ELSOC [Laboratorio de Investigación Social Abierta (LISA) - COES]. [https://lisa-coes.github.io/presentaciones/workshopelsoc-septiembre2022/workshopelsoc-sept2022.html](https://lisa-coes.github.io/presentaciones/workshopelsoc-septiembre2022/workshopelsoc-sept2022.html)

**2022 Enero.** Taller Introducción a la Ciencia Abierta: Pre-registros y Pre-prints [Laboratorio de Investigación Social Abierta (LISA) - COES]. [https://lisa-coes.github.io/presentaciones/tallerenero2022/tallerLISAenero2022.html](https://lisa-coes.github.io/presentaciones/tallerenero2022/tallerLISAenero2022.html)

**Diciembre 2019** "La demanda por igualdad y los caminos que cuentan con amplio respaldo ciudadano” (junto a Luis Maldonado, Julio Iturra, Jorge Atria & Francisco Meneses). Columna en CIPER. [https://www.ciperchile.cl/2019/12/06/la-demanda-por-igualdad-y-los-caminos-que-cuentan-con-amplio-respaldo-ciudadano/](https://www.ciperchile.cl/2019/12/06/la-demanda-por-igualdad-y-los-caminos-que-cuentan-con-amplio-respaldo-ciudadano/)

**Mayo 2018** “Redes Sociales: Aproximaciones Estructurales a la Cohesión en la Sociedad Chilena”. Comentario a la presentación del Prof. Vicente Espinoza. IDEA-USACH Santiago.

**Diciembre 2017** “Notas sobre los resultados de Chile en la última prueba internacional de formación ciudadana” Columna de opinión en CIPER junto a Daniel Miranda [https://ciperchile.cl/2017/12/28/notas-sobre-los-resultados-de-chile-en-la-ultima-prueba-internacional-de-formacion-ciudadana/](https://ciperchile.cl/2017/12/28/notas-sobre-los-resultados-de-chile-en-la-ultima-prueba-internacional-de-formacion-ciudadana/)

**Agosto 2017** “La meritocracia ¿una tragedia?”  Columna de opinión en El Mostrador. [http://www.elmostrador.cl/noticias/opinion/2017/08/21/la-meritocracia-una-tragedia](http://www.elmostrador.cl/noticias/opinion/2017/08/21/la-meritocracia-una-tragedia)

**Agosto 2017** Seminario COES-PNUD: “Discutiendo sobre las desigualdades en Chile”. Comentarista de presentación de Raimundo Frei sobre aspectos subjetivos de la desigualdad. Facultad de Economía, Universidad de Chile. 

**Octubre 2016** “Desigualdad y meritocracia”. Presentación en cátedra de investigación Santiago. Universidad Andrés Bello Santiago.

**Octubre 2016** “Mérito y preferencias redistributivas”. Presentación en Coloquio del Instituto de Sociología UC. Facultad de Ciencias Sociales, Universidad Católica Santiago.

**Octubre 2016** “La nueva Casen y las exigencias a la política social en Chile”. Columna de opinión en El Dínamo junto a Mauro Basaure. [https://www.eldinamo.cl/blog/la-nueva-casen-y-las-exigencias-a-la-politica-social-en-chile/](https://www.eldinamo.cl/blog/la-nueva-casen-y-las-exigencias-a-la-politica-social-en-chile/)

**Septiembre 2016** “CASEN y Cohesión: oportunidades y precauciones”. Columna de opinión en El Mostrador junto a Mauro Basaure. [http://www.elmostrador.cl/noticias/opinion/2016/09/29/casen-y-cohesion-oportunidades-y-precauciones/](http://www.elmostrador.cl/noticias/opinion/2016/09/29/casen-y-cohesion-oportunidades-y-precauciones/)

**Noviembre 2015** “Investigación sobre formación ciudadana en Chile”. Presentación en  Segundo Encuentro Nacional de Actores de la Formación Inicial de Docentes. CPEIP, Santiago.  

**Octubre 2015** “Conflicto y Cohesión social en Chile” Presentación de principales resultados Encuesta de Conflicto y Cohesión Social. Universidad Católica de Temuco. 

**Septiembre 2015** “Legitimización de la Desigualdad Social” Presentación en el Coloquio de Psicología Política junto al profesor Jim Sidanius (Harvard University). Facultad de Ciencias Sociales, Pontificia Universidad Católica de Chile. 

**Julio 2015** 2015 “Desigualdad y Justicia Social” Presentación resultados Encuesta COES. Fundación Chile 21, Santiago.  

**Junio 2015** “Desigualdad y distribución: ¿Qué piensan los chilenos?” Presentación resultados modulo desigualdad Encuesta de Conflicto y Cohesión Social. Facultad de Economía, Universidad de Chile. 

**Marzo 2015** “Crisis en la confianza política” Presentación de resultados modulo ciudadanía Ecuesta de Conflicto y Cohesión social. Facultad de Economía, Universidad de Chile. 

**Marzo 2015** “Familia, escuela y desigualdad en la formación ciudadana en Chile”. Presentación en Seminario Internacional sobre formación ciudadana en Chile. Universidad Católica, Santiago.

**Enero 2015** “Selección en particulares y la complicidad de los psicólogos”  Columna de opinión en El Mostrador [http://www.elmostrador.cl/noticias/opinion/2015/01/29/seleccion-en-particulares-y-la-complicidad-de-los-psicologs/](http://www.elmostrador.cl/noticias/opinion/2015/01/29/seleccion-en-particulares-y-la-complicidad-de-los-psicologs/)

**Enero 2015** “Herramientas para la investigación reproducible”. Organización de Taller de formación de postgrado.  Facultad de Ciencias Sociales, Universidad Católica, Santiago.

**Septiembre 2014** “De la educación cívica a la educación para la ciudadanía”.  Columna de opinión en El Mostrador [http://www.elmostrador.cl/noticias/opinion/2014/09/02/de-la-educacion-civica-a-la-educacion-para-la-ciudadania/](http://www.elmostrador.cl/noticias/opinion/2014/09/02/de-la-educacion-civica-a-la-educacion-para-la-ciudadania/)

## 5.5. ADMINISTRACIÓN UNIVERSITARIA y DIRECCIÓN ACADÉMICA: Indique los cargos más importantes de este tipo que ha desempeñado precisando la función, la institución y el tiempo de dedicación. Cuando corresponda, indique el lapso durante el cual ejerció el cargo.

•	Presidente del comité de investigación RC 42 (Social Psychology) de la International Sociological Association ISA (2023-2027)

•	Director de Investigación y Publicaciones, Facultad de Ciencias Sociales, Universidad de Chile (2022-       )

•	Coordinador del subcomité de datos de la Vicerrectoría de Investigación, Universidad de Chile (2023-2024)

•	Miembro del comité del Magister en Ciencias Sociales, mención Sociología de la Modernización (2022-2024)

•	Director  del grupo estudio de Sociología de FONDECYT (2018 - 2019 ).

•	Moderador del servicio de pre-prints Socarxiv (socopen.org) (2018 - )

•	Miembro del grupo estudio de Sociología de FONDECYT (2016 - 2017).

•	Consejo Académico, Instituto de Sociología, Pontificia Universidad Católica de Chile (2016 -2017). 

•	Consejo de Facultad, Facultad de Ciencias Sociales, Pontificia Universidad Católica de Chile (2016). 

•	Comité de Postgrado, Instituto de Sociología, Pontificia Universidad Católica de Chile (2015).

•	Comité Curricular, Instituto de Sociología, Pontificia Universidad Católica de Chile (2014). 

•	Subdirector FONDAP Centro de Estudios de Conflicto y Cohesión Social – COES (2013 - 2028)

•	Representante de América Latina en el comité de investigación 42 (RC42) de la International Sociological Association (ISA) (2014-2022).

# FORMACIÓN ACADÉMICA PROPIA: Si lo considera pertinente, señale los académicos a quienes Ud. considera sus formadores y maestros directos, indicando los aspectos específicos que definen ese carácter.

De los principales académicos influyentes en mi carrera destaco a:

- Prof. Domingo Asún Salazar: en pre-grado fue mi profesor guía en mi tesis de licenciatura sobre la creencia en la justicia y actitudes de discriminación. Él me motivó a profundizar en el espacio más social de la psicología, que finalmente influyó en especializarme en sociología en el doctorado. Destaco su gran capacidad formadora, interés por temas públicos, su disconformidad y paciencia.

- Prof. Bernd Wegener (Universidad de Humboldt): profesor de métodos cuantitativos en la Universidad de Humboldt, fue mi tutor de doctorado en sociología. Generosamente me invitó a ser parte del equipo de investigación comparativo sobre justicia distributiva, donde tuve la oportunidad de sumar a Chile como un país adicional al proyecto. De él aprendí  rigurosidad y escepticismo.

- Prof. Cristián Cox (UDP): especialista en sociología de la educación, fui su coinvestigador en dos proyectos FONDECYT sobre formación ciudadana y desigualdad política.  Ha sido una figura muy inspiradora por su reflexividad, mirada a largo plazo, e imaginación sociológica.

# FORMACIÓN DE NUEVOS ACADÉMICOS: Consigne el nombre y lugar de desempeño actual de los académicos que cultivan la disciplina, a la cual Ud. pertenece y, en cuya formación Ud. tuvo una responsabilidad principal. Indique en qué manera participó Ud. en dicha formación. Cuando sea el caso, señale la relación con proyectos comunes: publicaciones, dirección de memorias o tesis, etc.

Ciertamente no me puedo atribuir los éxitos de quienes alguna vez trabajaron conmigo, pero si puedo nombrar algunas personas más jóvenes con las que tuve la ventaja de trabajar en etapas iniciales de su carrera:

- Alejandro Plaza, guié su tesis de magíster en sociología, actualmente se doctora en sociología en la Universidad de Humboldt, Berlin.  

- Julio Iturra, fue tesista de magister en sociología, asistente de Fondecyt y de Fondap COES. Hemos coautoreado una serie de artículos y también  hemos presentado en conferencias internacionales. Actualmente se doctora en sociología en la Universidad de Bremen.

- Francisca Castro, guié su tesis de magister en sociología UC y fue también tesista de mi proyecto Fondecyt sobre economía moral de la meritocracia. Actualmente se doctora en ciencias políticas en la Universidad de Humboldt, Berlin.

- Gonzalo Franetovic, fue tesista de magister en sociología y asistente de Fondecyt. Actualmente se doctora en sociología en la Universidad de Milán.

- Ignacio Madero, fue mi asistente cuando trabajaba como investigador en Mide UC, coautoreamos en varios artículos. Fue profesor en sociología en FACSO, actualmente profesor asociado en sociología UC:

- Daniel Miranda, asistente en varios proyectos FONDECYT y también alumno de doctorado, tenemos varias coautorías y proyectos de investigación en conjunto. Trabajó en Mide UC y en psicología UC; acaba de ser seleccionado como profesor en psicología en FACSO.

- Ariel Azar, asistente en FONDECYT y coautor de artículos. Se doctoró en psicología en la Universidad de Chicago, actualmente profesor en Purdue University.

- Matías Placencio, tesista FONDECYT y colaborador en investigaciones sobre formación ciudadana, actualmente doctorándose en Boston College.

# DIFUSIÓN y COMUNICACIONES:

## LIBROS y PUBLICACIONES PERIÓDICAS:

### LIBROS y MONOGRAFIAS

Cox, C. & Castillo, J. (Eds.) (2015) Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

Castillo, J. (2011). The legitimacy of economic inequality: An empirical approach to the case of Chile. Boca R.: Dissertation.com.

### 8.1.2. CAPÍTULOS DE LIBROS & DOCUMENTOS DE TRABAJO.

García-Sánchez, E., García-Castro, J. D., Venegas, M., & Castillo, J.-C. (2022). The ideological underpinnings of distributive unfairness evaluations: Evidence from Latin America between 1997 and 2020. In H. Cakal, V. Smith, & D. Sirlopu (Eds.), Social Unrest in Latin America: Social Psychological Perspectives. Work in progress. https://osf.io/wz3rx/

Miranda, D., Castillo, J.-C., Miranda, C., & Conejeros, J. (2022). Trust in Political Institutions and Support for Authoritarianism in Latin American Students – Does Civic Knowledge Make a Diﬀerence? In A. Weinberg (Ed.), Psychology of Democracy: Of the People, By the People, For the People (pp. 173–194). Cambridge University Press. https://github.com/juancarloscastillo/authorit-trust_iccs-lat/blob/master/psych-of-dem-trust-auth-chapterproofs.pdf

Castillo, J., Miranda, D., & Bonilla, A. (2021). Measuring Attitudes Towards Gender Equality in International Tests: Implications for Their Validity. In J. Manzi, M. R. García, & S. Taut (Eds.), Validity of Educational Assessments in Chile and Latin America (pp. 259–280). Springer International Publishing. 

Miranda, Daniel, & Castillo, J.-C. (2021). Cambios en la participación política de los escolares. In S. Alé, K. Duarte, & D. Miranda (Eds.), Saltar el Torniquete: Reflexiones desde las juventudes de octubre (Primera edición, pp. 51–60). Fondo de Cultura Económica. 

Castillo, J.-C., Iturra, J., Meneses, F., & Andrade, V. (2021). Impuestos, redistribución y meritocracia: Cambios en Chile entre 1999 y 2019. In Atria, Jorge & C. Otero (Eds.), Impuestos justos para el Chile que viene (pp. 100–126). Fondo de Cultura Económica. https://www.impuestosjustos.io/

Castillo, JC., Miranda, D. & Bonilla, A. (2019 – aceptado) Medición de actitudes hacia la igualdad de derechos entre géneros en pruebas internacionales: Implicancias respecto a su validez. En J. Manzi, S. Taut & M. García (Eds.), Validez de los Sistemas de Evaluación en Chile y Latinoamérica (pp. 284–305). Santiago: Ediciones UC. 

Miranda, D. & Castillo, JC. (2018) The political socialization of attitudes towards equality of rights in comparative perspective. In A. Sandoval-Hernández, M. Isaac & D. Miranda (Eds.), Teaching Tolerance in a Globalized World. Dordrecht: Springer.

Miranda, D. , Castillo, JC. & Cumsille, P. (2018) Measurement model and invariance testing of scales measuring egalitarian values in ICCS. In A. Sandoval-Hernández, M. Isaac & D. Miranda (Eds.), Teaching Tolerance in a Globalized World. Dordrecht: Springer.

Bargsted, M., Castillo, J. & Somma, N. (2017) Trust in institutions in Latin America. En S. Zmerli & T. Van der Meer (Eds), Handbook of political trust. Northampton: Edward Elgar Publishing.

Castillo, J., Miranda, D. & Bonhomme, M. (2015) Desigualdad social y cambios en las expectativas de participación política de los estudiantes en chile. En C.Cox & J. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

Cox, C., Bascopé, M., Castillo, J., Miranda, D. & Bonhomme, M. (2015) Educación ciudadana en América Latina: Prioridades De los currículos escolares. En C.Cox & J. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

Miranda, D., Castillo, J, & Sandoval-Hernandez, A. (2015) Desigualdad y conocimiento cívico: Chile en comparación internacional. En C.Cox & J. Castillo (Eds.), Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

Olivos, F., Mackenna, B., Castillo, J. & Bargsted, M. (2015) Percepción de conflicto en Chile: Un análisis desde la opinión pública. En M.Castillo & C.Maldonado (Eds.),  Desigualdades: Tolerancia, legitimación y conflicto en las sociedades latinoamericanas. Santiago: RIL Editores.

Cox, C., Bascopé, M., Castillo, J., Bonhomme, M., Miranda, D. (2014) Educación Ciudadana en América Latina: Prioridades de los Currículos. Working Papers on Curriculum Issues,  UNESCO International Bureau of Education (IBE).

Castillo, J. & Olivos, F. (2014) Redistribución e impuestos: Un análisis desde la opinión pública. En Atria, J. Tributación en Sociedad: Impuestos y Redistribución en el Chile del Siglo XXI (143-166). Santiago: Uqbar.

Castillo, J. Miranda, D. & Carrasco, D. (2011). La percepción de desigual de la desigualdad (The unequal perception of inequality). Technical report IT1101, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

Castillo, J. & Carrasco, D. (2010). Sobre la estabilidad del autoritarismo: Un caso de medición de invarianza longitudinal (About the stability of authoritarianism: A case of measurement invariance). Technical report IT1008, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

Castillo, J. (2008). Factorial survey: Dimensions of Just Rewards. International Social Justice Project - Working Paper N°165. Berlin: Humboldt University.

Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. International Social Justice Project - Working Paper N°168. Berlin: Humboldt University.

Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Observatory on Inequality in Latin America – Working Paper N°24. Miami: University of Miami.

Schneider, S., & Castillo, J. (2007). Internal and External Attributions of Poverty - Germany 1991/ 2006. International Social Justice Project - Working Paper N°132, Berlin: Humboldt University.

Castillo, J., & Schneider, S. (2007). Internal and External Attributions of Poverty and Wealth. International Social Justice Project - Working Paper N°131, Berlin: Humboldt University.

Castillo, J. (2007) Legitimation and Justice Ideologies in contexts of extreme economic inequality. International Social Justice Project - Working Paper N°125, Berlin: Humboldt University.

Castillo, J., & Asun, D. (2002). Creencias en la Justicia en el Mundo: Un Estudio Preliminar en Relación a Actitudes de Intolerancia y Discriminación. In D. Paez (Ed.), Psicología Social. Buenos Aires: Prentice Hall.

### 8.1.3. REVISTAS NACIONALES: Se entiende aquellas que circulan principalmente sólo en el país de edición y que tengan comité editorial.

Castillo, J.-C., Meneses, F., Iturra, J., & Maldonado, L. (2019). Cambios en la percepción y justificación de desigualdad salarial en Chile. Análisis Del Año, 149–163.

Castillo, JC & Rivera,M. (2018) Poverty and wealth attributions: A second order confirmatory factor analysis model. Accepted in Psykhe (SCOPUS).

Atria, J., Amenábar, J., Sanchez, J., Castillo, JC & Cociña, M. (2017) Investigando a la élite económica: Lecciones y desafíos a partir del caso de Chile. Cultura, Hombre y Sociedad 27(2)5-36 (Scielo).

Castillo, J. (2016) Public opinion about just salaries in Chile: An exploratory study based on a factorial survey. Cuadernos ISUC 1(2)1-29. 

Castillo, J. (2014) Actitudes hacia el trabajo y justicia salarial en Chile. Temas de la Agenda Pública 66, 33-44 (Latindex).

Castillo, J., Madero, I. & Miranda, D. (2014) Educación, equidad y creencias respecto de la distribución económica. Sociedad Hoy 24, 13-31 (Latindex).

Castillo, J., Salamovich, A. & Madero, I. (2013) Clivajes partidarios y cambios en preferencias distributivas en Chile. Revista de Ciencia Política 33(2)469-488 (ISI).

Castillo, J. (2013) Contrastes entre la desigualdad objetiva y subjetiva en Chile. Temas de la Agenda Pública 57, 1-15 (Latindex).

Castillo, J., Miranda, D. & Carrasco, D. (2012) Percepción de desigualdad económica en Chile: Medición, sesgos y determinantes. Psykhé 21(1) 99-114 (SCOPUS).

Madero, I. & Castillo, J. (2012) Sobre el estudio empírico de la solidaridad: aproximaciones conceptuales y metodológicas. Polis 11(31) 391-409 (SCIELO).

Castillo, J. (2009). ¿Cuál es la Brecha Salarial Justa? Opinión Pública y Legitimación de la Desigualdad Económica en Chile. Estudios Públicos 113, 237-266.

### 8.1.4. REVISTAS INTERNACIONALES: Se entiende como aquellas que circulan ampliamente más allá del país de edición y que tengan comité editorial.

Castillo, J.-C., Iturra, J., Maldonado, L., Atria, J., & Meneses, F. (2023). A multidimensional approach for measuring meritocratic beliefs: Advantages, limitations and alternatives to the ISSP social inequality survey. International Journal of Sociology, Online first. https://doi.org/10.1080/00207659.2023.2274712

Castillo, J.-C., Bonhomme, M., Miranda, D., & Iturra, J. (2023). Social cohesion and attitudinal changes towards migration: A longitudinal perspective amid the COVID-19 pandemic. Frontiers in Sociology, 7, 1009567. https://doi.org/10.3389/fsoc.2022.1009567

Iturra, J., Castillo, J.-C., Rufs, C., & Maldonado, L. (2023). Percepción de desigualdad económica y su influencia sobre la justificación de las diferencias de ingreso legítimas. Estudios Sociológicos, 4(122).

Varas, S., Castillo, J.-C., & Ferrer, M. (2022). Enfermedades crónicas no transmisibles y el potencial efecto protector de la cohesión social en Chile. Revista IT Salud Comunitaria y  Sociedad, 9(9). add archive field. https://revistas.udelar.edu.uy/OJS/index.php/revista-it/article/view/945

Castillo, J.-C., García-Castro, J. D., & Venegas, M. (2022). Perception of economic inequality: Concepts, associated factors and prospects of a burgeoning research agenda. International Journal of Social Psychology, 37(1), 180–207. https://doi.org/10.1080/02134748.2021.2009275

Breznau, N., Rinke, E. M., Wuttke, A., Nguyen, H. H. V., Adem, M., Adriaans, J., Alvarez-Benjumea, A., Andersen, H. K., Auer, D., Azevedo, F., Bahnsen, O., Balzer, D., Bauer, G., Bauer, P. C., Baumann, M., Baute, S., Benoit, V., Bernauer, J., Berning, C., … Castillo, J,... Żółtak, T. (2022). Observing many researchers using the same data and hypothesis reveals a hidden universe of uncertainty. Proceedings of the National Academy of Sciences, 119(44), e2203150119. 

Franetovic, G., & Castillo, J. (2022). Preferences for Income Redistribution in Unequal Contexts: Changes in Latin America Between 2008 and 2018. Frontiers in Sociology, 7, 806458. https://doi.org/10.3389/fsoc.2022.806458

García-Castro, J. D., García-Sánchez, E., Willis, G. B., Castillo, J.-C., & Rodríguez-Bailón, R. (2022). Perceived economic inequality measures: Their reflection on objective inequalities and their effects on support for redistribution. Social Psychology, 53. https://econtent.hogrefe.com/doi/10.1027/1864-9335/a000498

García-Sánchez, E., Castillo, J.-C., Rodríguez-Bailón, R., & Willis, G. B. (2022). The two faces of support for redistribution in Colombia: Taxing the wealthy or assisting people in poverty. Accepted -  Frontiers in Sociology. https://doi.org/10.3389/fsoc.2022.773378

Frei, R., Castillo, J.-C., Herrera, R., & Suarez, J. I. (2020). ¿Fruto del esfuerzo? Los cambios en las atribuciones sobre pobreza y riqueza en Chile entre 1996 y 2015. Latin American Research Review, 55(3), 477–496.

Miranda, D., Castillo, J.-C., & Sandoval-Hernandez, A. (2020). Young Citizens Participation: Empirical Testing of a Conceptual Model. Youth & Society, 52(2), 251–271. 

Atria, J, Castillo, J.-C., Maldonado, L., & Ramirez, S. (2020). Economic elites’ attitudes toward meritocracy in chile: A moral economy perspective. American Behavioral Scientist, 64(9), 1219–1241. https://doi.org/10.1177/0002764220941214

Maldonado, L., Olivos, F., Castillo, J.-C., Atria, J., & Azar, A. (2019). Risk Exposure, Humanitarianism and Willingness to Pay for Universal Healthcare: A Cross-National Analysis of 28 Countries. Social Justice Research, 32(3), 349–383. https://doi.org/10.1007/s11211-019-00336-6

Martínez, M. L., Cumsille, P., Loyola, I., & Castillo, J.-C. (2020). Patterns of Civic and Political Commitment in Early Adolescence. The Journal of Early Adolescence, 40(1), 5–27. https://doi.org/10.1177/0272431618824714

Castillo, J.-C., Olivos, F., & Azar, A. (2019). Deserving a Just Pension: A Factorial Survey Approach. Social Science Quarterly, 100(1), 359–378. 

Atria, J., Castillo, J.-C., Maldonado, L., Ramírez, S., Atria, J., Castillo, J. C., Maldonado, L., & Ramírez, S. (2019). Studying meritocracy in an unequal context: Perspectives from chilean scholars. Universum, 34(2), 127–145. https://doi.org/10.4067/S0718-23762019000200127

Castillo, J. C., Torres, A., Atria, J., & Maldonado, L. (2019). Meritocracia y desigualdad económica: Percepciones, preferencias e implicancias. Revista Internacional de Sociología, 77(1), 117. https://doi.org/10.3989/ris.2019.77.1.17.114

Azar, A., Maldonado, L., Castillo, JC & Atria, J. (2018) Income, Egalitarianism, and Attitudes Towards Healthcare Policy: A Study on Public Attitudes in 29 Countries. Public Health 154:59-69 (ISI).

Guerra, C. & Castillo, J (2016) Sintomatología en adolescentes victimizados sexualmente: El rol del apoyo de la familia y del grupo de pares. Revista sobre la infancia y la adolescencia, 11:66-80 (Latindex).

Schneider, S. & Castillo, J. (2015) Poverty attributions and the perceived legitimacy of income inequalities: A comparison of East and West Germany. Social Psycholgy Quarterly 78(3):263-282 (ISI).

Castillo, J., Joignant, A., Palacios, D., & Tham, M. (2015) Inequality, distributive justice and political participation. Bulletin of Latin American Research 34(4)486-50 (ISI).

Bascopé, M., Bonhomme, M., Cox, C., Castillo, J., Miranda, D. (2015) Curricular Guidelines and Citizenship Education in Latin American Schools. Revista Latinoamericana de Ciencias Sociales, Niñez & Juventud 13(2):1169-1190 (Scielo).

Zmerli, S. & Castillo, J. (2015) Inequality and political trust. How objective and subjective inequality affects Latin American democracies. Social Science Research 72, 179-192 (ISI).

Castillo, J., Cox, C., Miranda, D., Bascopé, M. & Bonhomme, M. (2014) Mitigating the Political Participation Gap from the School: The Roles of Civic Knowledge and Classroom Climate. Journal of Youth Studies 18 (1) 16-35 (ISI).

Castillo, J., Cox, C., Miranda, D., Bascopé, M. & Bonhomme, M. (2014) Social inequality and changes in students’ expected political participation in Chile. Education, citizenship & social justice 9 (2) 140-156 (SCOPUS).

Factor, R., Castillo, J. & Rattner, A (2014) Procedural justice, religiosity and minorities. Police Practice and Research 15 (2) 130-142 (SCOPUS).

Castillo, J., Miranda, D. & Madero, I. (2013) Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Latin American Research Review 48(1) 155-173 (ISI).

Preiss, D., Castillo, J., Flotts, P. & San Martin, E (2013).  Assessment of argumentative writing and critical thinking in higher education: Educational correlates and gender differences. Learning and Individual Differences 28, 193-203 (ISI).

Preiss, D., Castillo, J., Grigorenko, H. & Manzi, J. (2013) Argumentative writing and academic achievement: A longitudinal study. Learning and Individual Differences 28, 204-211 (ISI).

Castillo, J. (2012) Una aproximación multidimensional al estudio de la legitimidad de la desigualdad económica. Revista Internacional de Sociología 3(70) 533-560 (ISI).

Castillo, J. Leal, P., Madero I. & Miranda, D. (2012) ¿Son los chilenos igualmente solidarios? La influencia de los recursos personales en las donaciones de dinero. Opinao Publica 18(1) 154-176 (SCOPUS).

Castillo, J. (2012) Is inequality becoming just? Changes in public opinion about economic distribution in Chile. Bulleting of Latin American Research 31(1) 1-18 (ISI).

Castillo, J. (2011) Legitimacy of inequality in a highly unequal context: Evidence from the chilean case. Social Justice Research 24(4) 314-340 (ISI).

## 8.2. OTROS ESCRITOS E INFORMES.

2023- Castillo, J.-C., Espinoza, V., & Barozet, E.  Cohesión social en Chile en tiempos de cambio: Indicadores, perfiles y factores asociados [Documentos de Proyecto (LC/TS.2022/3)]. CEPAL.

2017 – Consultoría UNESCO: Análisis de resultados de pruebas de Ciudadanía y convivencia en escuelas de Bogotá, realizado para el informe de Evaluación del Proyecto Educación para la Ciudadanía y la Convivencia (PECC). 

2017 – Consultoría para la Agencia de Calidad de la Educación: Elaboración de preguntas para el módulo de Participación y Vida Democrática de los Indicadores de Desarrollo personal y Social (IDPS).

2015 – Asesoría al Centro de Políticas Públicas UC en la elaboración del “Estudio exploratorio sobre Confianza Institucional local: Percepciones y propuestas desde la escala municipal”.

2015 – Consultoría para la Agencia de Calidad de la Educación: Revisión de aspectos conceptuales y metodológicos del Indicador de Participación y Vida Democrática.

## 8.3. PONENCIAS A CONGRESOS.

Castillo, J.-C. (2024a, January). Herramientas de Ciencia Abierta: Apertura y reproducibilidad de proyectos de investigación [Proyecto Ingeniería 2030 de la Facultad de Ingeniería de la Universidad de Valparaíso]. https://uv.cl/archivo-noticias-uv/26426-director-de-investigacion-de-la-facultad-de-ciencias-sociales-uchile-dicto-taller-sobre-ciencia-abierta

Castillo, J.-C. (2024b, January). Social cohesion and attitudinal changes toward migration [GlobaLab Bremen Conversations on Global Solidarity].

Castillo, J.-C. (2024c, April). Social Inequalities in the Global South [Inequality Conference - Exellence Cluster  The Politics of Inequality]. https://inequality-conference.de/session/roundtable-global-south-tbd/

Maldonado, L., Castillo, J.-C., & Iturra, J. (2024, April). Does information about inequality affects opportunity beliefs? Results from a survey experiment [Poster presented at the Inequality Conference - Exellence Cluster  The Politics of Inequality]. https://inequality-conference.de/

Iturra, J., Castillo, J.-C., & Maldonado, L. (2023, July). Perceptions and preferences about income taxes: A factorial survey approach [ESRA].

Castillo, J.-C. (2023a, January). Diseño y gestión de proyectos de investigación abiertos [Escuela de Verano Conocimiento y Ciencia Abierta - Universidad Central].

Castillo, J.-C. (2023b, January). Flujo y Componentes de la Investigación Abierta [9o Congreso de Bibliotecas Universitarias y Especializadas, Universidad de Chile].

Castillo, J.-C., Cáceres, I., & Carrasco, K. (2023, June). Concepts, Measurement and Indicators of Social Cohesion: A Longitudinal Perspective [ISA XX World Congress of Sociology].

Castillo, J.-C., & Carrasco, K. (2023a, Agosto). Brechas de género en la percepción y justificación de desigualdad salarial en Chile 1999-2019. [Conferencia DEMOSAL].

Castillo, J.-C., & Carrasco, K. (2023b, June). The socialization of meritocracy at school and the justification of economic inequality [ISA XX World Congress of Sociology].

Castillo, J.-C., Carrasco, K., & Iturra, J. (2023, July). Perceived salary and gender gaps in survey research [ESRA].

Castillo, J.-C., Carrasco, K., & Salgado, M. (2023, June). The socialization of meritocracy at school and the justification of economic inequality [EFFORT Conference].

Castillo, J.-C., Carrasco, K., Salgado, M., Moyano, C., & Angelcos, N. (2023, Agosto). Socialización de la meritocracia en la escuela y justificación de la desigualdad económica [Conferencia DEMOSAL].

Castillo, J.-C. (2022a, Enero). Protocolos reproducibles y reportes dinámicos con R / Rmarkdown [Laboratorio de Investigación Social Abierta (LISA) - COES]. https://lisa-coes.github.io/presentaciones/tallerRmarkdown-IPOEnero2022/taller-reprod-enero2022.html

Castillo, J.-C. (2022b, March 29). Presentación Cohesión social en Chile en tiempos de cambio: Indicadores, perfiles y factores asociados [Presentación Seminario CEPAL-COES]. https://ocscoes.github.io/presentaciones/CEPAL2022cohesionELSOC.html

Castillo, J.-C. (2022c, June 2). Herramientas para la apertura del flujo de investigación científica [Presentación en el seminario: Ciencia abierta, ¿es ciencia accesible?]. https://lisa-coes.github.io/presentaciones/Ibero-MEX-Jun2022/iberomex2022.html

Castillo, J.-C. (2022d, September 22). Percepciones de desigualdad en Chile [Comentario en Seminario: ¿Cuánto cambiaron las percepciones de desigualdad tras el estallido social?]. /presentations/cep-desigualdad-2022/cep-percdes-2022.html

Castillo, J.-C., & Bargsted, M. (2022, January 21). Measurement and Analysis of Social Cohesion [Research Institute Social Cohesion - Jahrestagung Forschungscluster 2]. https://ocscoes.github.io/presentaciones/RISC-bremen-january2022.html

Castillo, J.-C., & Carrasco, K. (2022, September). Taller Preregistros ELSOC [Laboratorio de Investigación Social Abierta (LISA) - COES]. https://lisa-coes.github.io/presentaciones/workshopelsoc-septiembre2022/workshopelsoc-sept2022.html

Castillo, J.-C., & Iturra, J. (2022, Enero). Taller Introducción a la Ciencia Abierta: Pre-registros y Pre-prints [Laboratorio de Investigación Social Abierta (LISA) – COES]. https://lisa-coes.github.io/presentaciones/tallerenero2022/tallerLISAenero2022.html

Miranda, D., & Castillo, J.-C. (2022, October). Youth dispositions to participate in disruptive and pacific actions [Conferece INVALSI  data -  A tool for teaching and scientific research].

Castillo, J.-C., Carrasco, K., & Cáceres, I. (2021, September 30). Concepts and measurement of social cohesion in international perspective [3rd Akademie für Soziologie (AS) Conference: Cohesive Societies? Analytical-empirical Perspectives]. https://ocscoes.github.io/presentaciones/presentation-cohesive-societies.html

Castillo, J.-C., Iturra, J., Meneses, F., & Venegas, M. (2021, November). Socialización de la meritocracia: El rol de la familia y la escuela. VIII Conferencia Internacional COES: Cohesión Social en tiempos turbulentos, Santiago. https://formacionciudadana.github.io/presentations/coes2021/soc-merit/coes2021.html#1

Iturra, J., & Castillo, J.-C. (2020, June). Dinámicas de legitimación: Percepción de desigualdad actual y justificación de desigualdad futura [Seminario ELSOC Cambio Social en Chile]. https://jciturras.github.io/dinamic-legit/slides/dinamic-legit_elsoc.html#1

Castillo, JC. (2018) Open academic writing: An Atom-based workflow for social scientists. SocArxiv: Open Social Science Scholarship Conference (Oct. 17-18). University of Maryland.

Castillo, JC. (2018) Perceptions and preferences about meritocracy in international comparison. Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center

Castillo, JC. & Jaime-Castillo, A. (2018) Reciprocity and Distributive Justice. Joint session organized for the Research Committee 42 (Social Psychology)  and 45 (Rational Choice) at the Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center

Castillo, JC. (2017) Percepciones y legitimación de la desigualdad: Mérito e Instituciones. Panel Congreso Latinoamericano de Sociología (Diciembre 2-7). Montevideo, Universidad de la República. 

Castillo, JC. (2017) Meritocracia y preferencias redistributivas. Panel Conferencia COES (Noviembre 8-9. Viña del Mar, Universidad Adolfo Ibañez. 

Castillo, JC. (2017) Meritocratic beliefs and economic inequality. Colloquium of Macro Sociology (Julio 12). Berlin, Humboldt University.

Castillo, JC. & Miranda, D. (2017) Class and Status as Predictors of Inclusive Attitudes Towards Immigrants, Minorities and Gender. 7th IEA International Research Conference (IRC) (June 28-30). Prague, Charles University.

Castillo, JC. (2016) Economic Inequality, Distributive Preferences and Political Outcomes (I & II). Sessions organized for the Research Committee 42 (Social Psychology) at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria.

Castillo, JC. (2016) Inequality, Distributive Preferences and Types of Participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria. 

Castillo, JC. & Miranda, D. (2015) Origen social, conocimiento cívico y participación en la escuela. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Miranda, D. & Castillo, JC.  (2015) Lo civil y lo civico: Hacia un modelo conceptual y de medición de ciudadanía escolar. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Castillo, J., Olivos, F. & Azar, A. (2015) Justice of pensions: A factorial survey approach. Paper presented at the Congress of the World Association for Public Opinion Research – WAPOR (June 16-19). Buenos Aires, Argentina. 

Castillo, J. (2014) Inequality, justice beliefs and political participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 13-19). Yokohama, Japan. 

Castillo, J. (2014) Economic inequality, social justice and political participation in Latin America. Poster presented at the Herrenhausen Conference: “Re-thinking Social Inequality” (May 12-14) Herrenausen Palace, Hannover, Germany.

Bargsted, M., Castillo, J. & Somma, N. (2014) Political trust in Latin America. Paper presented at the authors workshop of the Handbook of Political Trust (Van der Meer, T. & Zmerli, S., eds.) (May 14-18) Goethe University, Frankfurt, Germany.

Zmerli, S. & Castillo, J. (2013) Income inequality and social trust in Latin American societies. Paper presented at the “7th ECPR General Conference”, Panel:  Dismantling Democracy: The Challenge of Inequality to Political Engagement. (September 4-7). Bordeaux.

Castillo, J., Miranda, D., Bonhomme, M., Cox, C. & Bascopé, M. (2013) Mitigating the participation gap from the school: The role of civic knowledge and classroom climate. Paper presented at the research colloquium of the Data Processing and Research Center, International Association for the Evaluation of the Educational Achievement (IEA). (August 7). Hamburg, Germany.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Desigualdad económica y cambios en las expectativas de participación de estudiantes en Chile. Paper presented at the “Congreso Interdisciplinario de Investigación en Educación – CIEE” (August 23-24). Santiago de Chile.

Castillo, J., Madero, I., Miranda, D. & Escobar, J. (2012) Education, equity and distributive beliefs: Evidence from the chilean case. Paper presented at the International Sociological Association - ISA Forum (August 1-4). Buenos Aires.

Zmerli, S. & Castillo, J. (2012) Income inequality and political support: How objective and subjective inequality affect Latin Américan democracies. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Social inequality and changes in students' expected political participation in Chile. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., Madero, I. & Escobar, J. (2012) Social origin and citizenship participation in Latin American schools. Paper presented at AERA Conference (April 13-17). Vancouver.

Castillo, J., Salamovich, A. & Miranda, D. (2011) Partisan cleavages and distributive preferences: A cross sectional time comparison. Poster presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 9-12). Istanbul: Bilgi University.

Castillo, J. (2010).  Is inequality becoming just? Changes in public opinion about economic inequality in Chile. Paper presented at the "XXIX International Congress of the Latin American Studies Association" (Oct.6-9). Toronto: Sheraton Conference Center.

Castillo, J. (2010). Higher salaries but stable inequality? A cross-sectional comparison of attitudes towards economic distribution. Paper presented at the "13th biennal conference of the International Society for Justice Research" (Aug.21-24). Banff (Canada): The Banff Centre. 

Castillo, J. (2009). Herkunftsbedingte Disparitäten im Hochschulzugang in Chile und Deutschland (Origin related inequalities in the access to higher education in Chile and Germany). Presentation at the conference “Herausforderungen der Globalisierung” (Nov. 20-21) Berlin: Iberoamerikanisches Institut.

Castillo, J. (2009). Perception and Legitimacy of Economic Inequality in Chile. Paper presented at the 5th ECPR General Conference (Sept. 10-12). Potsdam: Potsdam University.

Castillo, J. (2009). What are Just Salaries for Different Occupations in Chile? Paper presented at the 21st World Congress of Political Science – IPSA (July 12-16). Santiago de Chile: Universidad de Chile.

Castillo, J. (2009). Consensus and Legitimacy of Earnings Inequality. Presentation at the International Social Justice Project Workshop (May 6-10). Haifa: Haifa University, Israel.

Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. Paper presented at the Annual Meeting of the American Political Science Association (Aug. 28-31). Boston: Conference Center

Castillo, J. (2008). On the Justice of Occupational Earnings in Chile: A Factorial Survey Analysis. Presentation at the 12th Conference of the International Society for Justice Research (August 14-17). Adelaide: Flinders University.

Castillo, J., & Schneider, S. (2008). The Legitimacy of the Distributive System: A Comparison of Germany and Chile. Paper presented at the 31st Conference of the International Society of Political Psychology – ISPP (July 9-12). Paris: Sciences Po.

Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Paper presented at the conference Intra- and inter- generational Transmission of Inequality (Feb. 28-29). Mexico: Regional Bureau for Latin America and the Caribbean of United Nations Development Program (RBLAC-UNDP).

Castillo, J. (2007). Explanations of Poverty: A Comparison of Germany, the Czech Republic and Chile. Persentation at the International Social Justice Project Workshop (April 27-28). Budapest: Social Sciences Faculty, Eötvös Loránd University.

Castillo, J. (2007). Legitimation and Justice Ideologies in Contexts of Extreme Economic Inequalities. Paper presented at the 30th Conference of the International Society of Political Psychology – ISPP (July 4-7). Portland: Embassy Suites Hotel.

Castillo, J. (2007). Justice Ideologies and Attributions of Poverty in Comparative Perspective. Paper presented at the conference Law and Society in the 21st Century (July 15-28). Berlin: Humboldt University.

# ACTIVIDADES ACADÉMICAS QUE DESARROLLA A LA FECHA DE ESTE CURRÍCULO FUERA DE LA UNIVERSIDAD DE CHILE: Indique institución o entidad, cargo que desempeña, breve descripción de la actividad que realiza y horas semanales de dedicación.

# ACTIVIDAD PROFESIONAL: Señale las actividades profesionales en que haya participado y que, a su juicio, han contribuido a su actividad académica. Indicar, si fuere el caso, el nombre de la institución donde haya prestado servicios, tipo de actividad, objetivo de la misma y horas de dedicación semanal.

- ver punto 4 cronología laboral

# ADMINISTRACIÓN NO UNIVERSITARIA: Profesional, científica, cultural, gremial u otras. Consigne la institución, el cargo, lapso de desempeño y otros antecedentes que estime pertinentes.

# SOCIEDADES ARTÍSTICAS, CIENTÍFICAS, ETC.:

# RECONOCIMIENTO DE LA OBRA PUBLICADA:

Lo que puedo mencionar aquí son algunos logros alcanzados en la plataforma Researchgate.com, donde difundo parte de mi trabajo académico. Durante este año 2018, en varias ocasiones mis trabajos han sido los más leídos de mi instituto, acumulando a la fecha más de 7000 lecturas. Mi artículo “¿Cuál es la brecha salarial justa?” posee a la fecha más de 1000 lecturas. 

# REFERENCIAS: 

Nacionales:

- Profesora Kathya Araujo, IDEA-USACH.

- Profesor Christian Cox, Universidad Diego Portales

- Profesora Gabriela Rubilar, FACSO Universidad de Chile.

- Profesor Dante Contreras. FEN Universidad de Chile / Director COES.

- Profesor Matías Bargsted, Director Instituto de Sociología UC.

Internacionales:

- Prof. Sonja Zmerli, Sciences Po Grenoble. [https://www.sciencespo-grenoble.fr/membres/zmerli-sonja/](https://www.sciencespo-grenoble.fr/membres/zmerli-sonja/)

- Prof. Leslie McCall, Associate Director, Stone Center on Socio Economic Inequality. The Graduate Center, City University of New York. [https://stonecenter.gc.cuny.edu/people/mccall-leslie/](https://stonecenter.gc.cuny.edu/people/mccall-leslie/ )

- Prof. Olaf Groh-Samberg, Research Institute on Social Cohesion, University of Bremen. [https://www.socium.uni-bremen.de/ueber-das-socium/mitglieder/olaf-groh-samberg/](https://www.socium.uni-bremen.de/ueber-das-socium/mitglieder/olaf-groh-samberg/)

# CREATIVIDAD ACADÉMICA:

# JERARQUIZACIÓN DE PROYECTOS:

Mi proyecto más importante de los últimos 9 años es el Centro de Estudios de Conflicto y Cohesión Social – COES, donde fui subdirector y actualmente investigador principal. Este centro es una iniciativa financiada por FONDAP-CONICYT y reúne a más de 40 investigadores de la Universidad de Chile y Universidad Católica, como instituciones principales, y Universidad Diego Portales y Adolfo Ibañez como instituciones asociadas. El trabajo en COES ha implicado montar una serie de procedimientos y formas de colaboración académica orientadas al trabajo interdisciplinario en ciencias sociales en Chile, junto con exigentes metas de publicación de alto impacto. Al cabo de 9 años hemos logrado posicionarnos en el medio nacional e internacional, insertar capital humano avanzado, realizar capacitación y un gran número de actividades de difusión, lo que ha resultado muy satisfactorio en términos profesionales. En el marco de COES he desarrollado mi investigación en la relación entre meritocracia y redistribución, así como también en la transmisión intergeneracional de la desigualdad política, ambos financiados con proyectos FONDECYT. 

Mi línea de investigación principal en justicia distributiva ha sido artículada los últimos años en torno a dos proyectos Fondecyt Regular: Economía moral de la meritocracia (2016-2020), y Meritocracia en la escuela (EDUMER): Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile (2021-2025). En ambos han participado coinvestigadores de otras universidades, hemos desarrollado investigación cualitativa y cuantitativa, hemos presentado resultados en prestigiosas conferencias internacionales, y por supuesto publicado en revistas de corriente principal.

Mi línea de investigación secundaria también se a relacionado con proyectos Fondecyt donde he participado como coinvestigador de Cristián Cox: Socialización política y experiencia escolar - Chile en contexto internacional (2012-2015), y Socialización política y educación para la ciudadanía - El rol de la familia y de la escuela (2018-2021). Actualmente desarrollo investigación que vincula formación ciudadana con desigualdades digitales en el Núcleo Milenio en Oportunidades y Desigualdades Digitales -NUDOS (2023-2025), donde soy investigador principal y donde participa parte del equipo de formación ciudadana de los proyectos Fondecyt anteriores.

# ASPECTOS GLOBALES DE LA OBRA EXPUESTA:

En este apartado lo he organizado en torno a tres áreas principales de desempeño y proyección académica: docencia, investigación y extensión.

1) Docencia:

En docencia mi principal fortaleza es la enseñanza de metodología y técnicas de investigación social cuantitativa en pregrado y postgrado, área en la que me especialicé en mi doctorado en el departamento de Métodos de Investigación de la Universidad de Humboldt. Además de la enseñanza en cursos de pre y postgrado, mi objetivo es ir más allá de la mera transmisión de técnicas de análisis, poniendo énfasis en los destinatarios de los conocimientos que se están produciendo, así como también en su potencial impacto. Por ello, profundizo en temas de ciencia abierta,  como son la transparencia en los procesos de análisis, herramientas de visualización y presentación de resultados, así como también en escritura académica. 

En línea con esta orientación hacia la ciencia abierta, los últimos años he implementado en mis cursos estrategias de trabajo colaborativo, reproducibilidad de los resultados y  de comunicación de productos científicos. Para ello uso herramientas de software libre y trabajo de análisis y escritura en texto plano, que favorecen tanto la reproducibilidad como el control de versiones en grupos de investigación. Dentro de estas plataformas de trabajo que pretendo seguir integrando en mi docencia puedo mencionar R/Rstudio y sus librerías de ciencia de datos (Markdown/Rmarkdown, knitr, dplyr y en general tidyverse), así como también software complementario afín a la producción científica en un marco de ciencia abierta, como Latex, Pandoc, Quarto, y Git/GitHub. Si bien esto plantea un entorno exigente para estudiantes de sociología, las evaluaciones de los cursos que he realizado con este enfoque han sido muy positivas (por sobre el promedio de la Universidad y del Instituto de Sociología).

2) Investigación

Mi agenda en temas de investigación se proyecta en tres temas principales asociados a proyectos con financiamiento vigente: meritocracia, formación ciudadana y cohesión social.

•	Meritocracia: este tema es parte de mi línea principal de investigación de los últimos 10 años, que se caracteriza por vincular aspectos subjetivos y objetivos de la desigualdad económica. Me interesa saber en qué medida características individuales, el contexto interpersonal y macrosocial se relacionan con distintas maneras de percibir, desafiar y justificar la desigualdad. Junto a ello, también son relevantes  las consecuencias de percepción y justificación de desigualdad en aspectos como el comportamiento político y las preferencias redistributivas. Todo esto tiene como principal contexto la situación de alta desigualdad económica en Chile, sus orígenes históricos y sus consecuencias para la vida social. En este marco un concepto clave que permite asociar valoraciones subjetivas con la legitimación de estructuras de desigualdad es el de meritocracia. Actualmente estoy en el último año de  un proyecto FONDECYT regular que intenta vincular percepciones y preferencias sobre meritocracia con distintos aspectos de la formación ciudadana en la etapa escolar. Este proyecto se basa en un Fondecyt regular previo que estudió la relación entre  meritocracia y preferencias redistributivas. En un marco conceptual de economía moral, el objetivo principal de esta investigación fue estudiar la relación entre meritocracia (percepciones y preferencias) y las actitudes frente a la redistribución en ámbitos generales (por ejemplo, impuestos) y también específicos (salud, educación y pensiones). Los dos primeros años del proyecto trabajamos con metodologías cualitativas, y en esta fase siguiente nos centraremos en el análisis de datos secundarios de encuestas comparativas (como ISSP) y longitudinales (ELSOC), así como también en el desarrollo de experimentos de encuesta. 

•	Formación ciudadana: esta es mi línea secundaria, donde fui coinvestigador de dos FONDECYT regular (2012-2015 y 2018-2021), y que actualmente se proyecta en el Núcleo Milenio de Oportunidades y Desigualdades Digitales (NUDOS). El principal foco de estudio en esta línea ha sido la transmisión intergeneracional de la desigualdad política, dando cuenta de cómo la escuela y la familia influyen en distintos ámbitos de desempeño político de estudiantes, como conocimiento cívico, participación, ciudadanía digital y actitudes democráticas. Los métodos combinan levantamiento cualitativo, cuantitativo, y también análisis de datos secundarios del estudio ICCS (International Civic and Citizenship Education Study), en sus versiones 2009 y 2016. En este proyecto el objetivo principal es estudiar el rol de las familias en la formación ciudadana, ya que investigaciones internacionales señalan que gran parte de las diferencias de origen de las/os estudiantes en temas políticos no alcanzan a ser mitigadas por la escuela. De la misma manera que el proyecto anterior, se considera la formación de investigadores en roles de tesistas y asistentes de investigación.

•	Cohesión social: parte importante de mi agenda de investigación de los últimos años se relaciona con el Centro de Estudios de Conflicto y Cohesión Social, desde el año 2013. Aquí mi rol combina gestión académica del centro y también participación en proyectos internos transversales como el Observatorio de Cohesión Social y también ELSOC (Estudio Longitudinal Social de Chile). Además dirijo la línea de investigación de interacción social, en temáticas como redes sociales, relaciones intergrupales y también clivajes sociales. He puesto énfasis en vincular las bases de datos levantadas por COES (Observatorio de Huelgas Laborales, Observatorio de Conflictos y ELSOC) con la docencia, con un énfasis en el estudio del cambio social mediante la estimación de modelos longitudinales para datos panel.

3) Extensión

La mayor parte de mis labores de formación y de extensión se vinculan con la promoción de la ciencia abierta. Junto con haber diseñado y desarrollado el curso de Investigación Social Abierta para pregrado en FACSO (https://cienciasocialabierta.netlify.app/), también he sido invitado a una serie de charlas en distintas universidades, he colaborado con el repositorio de pre-prints de ciencias sociales SocArxiv, y he estado liderando el Laboratorio de Investigación Social Abierta LISA (https://lisa-coes.com/). Desde este espacio hemos logrado sistematizar y promover una serie de prácticas y herramientas de ciencia abierta en las distintas etapas del ciclo de investigación. También hemos creado herramientas como el protocolo de investigación reproducible IPO (https://lisa-coes.com/ipo-repro/), que es una propuesta de organización de la información en proyectos de investigación. El último año desarrollamos una encuesta de conocimiento y prácticas de ciencia abierta para academicas y academicos de ciencias sociales, cuyos datos actualmente nos encontramos analizado y próximamente publicaremos. Finalmente, en la actualidad soy coordinador del subcomité de datos abiertos de la Vicerrectoría de Investigación (VID), donde me invitaron en el marco del proyecto Ines Ciencia Abierta de ANID con el objetivo de desarrollar un reglamento de uso de datos abiertos para la universidad.

# ANTECEDENTES ADICIONALES

**Estadías de investigación y visitas como profesor (visiting professor)**:

•	Profesor visitante en el Instituto de Investigación en Cohesión Social de la Universidad de Bremen  (con profesor Olaf Groh-Samberg). Bremen,  Junio y Julio de 2024.

•	Profesor visitante en el Instituto de Investigación en Cohesión Social de la Universidad de Bremen  (con profesor Olaf Groh-Samberg). Bremen, Julio de 2022.

•	Invitación a profesor visitante en Sciences Po Grenoble, con la profesora Sonja Zmerli en Diciembre de 2020 (cancelada por pandemia).

•	Profesor visitante en Departamento de Macrosociología, Humboldt Universität zu Berlin (con profesor Steffen Mau). Berlin, Junio y Julio de 2017.

•	Profesor visitante en Bremen International Graduate School of Social Sciences, Universidad de Bremen (con profesor Klaus Boehnke). Junio y Julio de 2016.

•	Profesor visitante en Wissenschaftszentrum Berlin für Sozialforschung  – WZB (con profesor Wolfgang Merkel). Julio de 2015.

•	Data Processing and Research Center (DPC), International Association for the Evaluation of Educational Achievement (IEA). Hamburgo, Diciembre 2014.

•	Data Processing and Research Center (DPC), International Association for the Evaluation of Educational Achievement (IEA). Hamburgo, Julio-Agosto 2013.

**Software de análisis estadísitico y reporte**: utilizo y enseño  herramientas coherentes con el trabajo en ciencia abierta, es decir, de fuente abierta (open-source) y además libres (sin licencia de pago):

•	R / Rstudio: para análisis de datos y visualización


•	Latex / Markdown: para escritura académica reproducible (en texto plano)

•	Knitr: para generar documentos reproducibles en pdf/HTML.

•	Beamer (Latex) y Xaringan (Markdown/css) para generación de presentaciones

**Idiomas**: Inglés (avanzado), Alemán (avanzado).

**Revisor ad-hoc de revistas** (American Sociological Review, Social Justice Research, Review in Social Stratification & Mobility, Revista Internacional de Sociología, Current Sociology, Journal of Youth Studies, European Sociological Review, Latin American Research Review, Learning & Individual Differences, entre otras).

# RESUMEN 

Indique si entrega o no, información en cada capítulo y sub-capítulo del currículo, marcando con una letra equis (x) la línea respectiva.

[tabla]

# Anexos

\includepdf[pages={2,3,4}]{anexos/titulos.pdf}

